# Network
hidden_size: 768
video_size: 1024
# audio_size: 1024 #1582
# training
epoch: 50
BATCH_SIZE: 64
MIN_BATCH_SIZE: 1 #16
EVAL_BATCH_SIZE: 1 #16
BERT_LR_MULT: 0.001
LR_BASE: 0.00005 #5e-5 
LR_DECAY_R: 0.2
LR_DECAY_LIST: [5,25] #25
WARMUP_EPOCH: 0
MAX_EPOCH: 20
GRAD_NORM_CLIP: -1

OPT_FTW: AdamW 
OPT_PARAMS: {betas: '(0.9, 0.98)', eps: '1e-9'}
EPOPH_FTW: 1
OPT_FTW: AdamW
LR_BASE_FTW: 0.001 #0.001
OPT_PARAMS_FTW: {betas: '(0.9, 0.98)', eps: '1e-9'}
